global:
  provider:
    registry:
      fqdn: docker.io 
    name: azure 
    storage:
      provisioner: kubernetes.io/azure-disk
      reclaimPolicy: Delete 
      parameters:
        storageaccounttype: Standard_LRS
        kind: managed 

zookeeper:
  disableHostPort: true
  resources:
    cpu: 200m
    memory: 512Mi
  
kafka:
  disableHostPort: true
  resources:
    cpu: 200m
    memory: 1Gi
  loadBalancer:
    enabled: false
  tls:
    enabled: false
  metricReporter:
    enabled: true
  configOverrides:
    server:
    - auto.create.topics.enable=true

schemaregistry:
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071 

connect:
  image:
    repository: cnfldemos/cp-server-connect-operator-datagen 
  tls:
    enabled: false
  loadBalancer:
    enabled: false
  dependencies:
    kafka:
      brokerCount: 1
      bootstrapEndpoint: kafka:9071
    schemaregistry:
      enabled: true 
      url: http://schemaregistry:8081 

controlcenter:
  loadBalancer:
    enabled: false
  dependencies:
    c3KafkaCluster:
      zookeeper:
        endpoint: zookeeper:2181
      bootstrapEndpoint: kafka:9071
      brokerCount: 1
    connectCluster:
      enabled: true
      url: http://connectors:8083
    schemaRegistry:
      enabled: true
      url: http://schemaregistry:8081 

