apiVersion: v1
kind: Pod
metadata:
  namespace: operator
  name: client-console
spec:
  containers:
  - name: client-console
    image: docker.io/confluentinc/cp-server-operator:6.0.0.0
    command: [sleep, "86400"]
    volumeMounts:
    - name: kafka-client-properties
      mountPath: /etc/kafka-client-properties/
    - name: destination-cluster-client-properties
      mountPath: /etc/destination-cluster-client-properties/
  volumes:
  - name: kafka-client-properties
    secret:
      secretName: kafka-client.properties
  - name: destination-cluster-client-properties
    secret:
      secretName: destination-cluster-client.properties

